### ISSUE TITLE
Names of Bosses are blank in Heroku Deployment

### ISSUE THREAD

**Issue by ghost** [walfie/gbf-raidfinder#105]
Dear Developers,

I tried to setup my own raid finder on Heroku. Based on the "one-button" setup, it line up smoothly.

However, I cannot see any bosses on list to select. Could you tell how to fix this problem? 

Should I manually add name of bosses?

**Comment by walfie** [comment]
It should populate the boss list automatically, assuming your twitter API credentials are correct. Do you see anything in the Heroku error logs?

**Comment by VictusNoctus** [comment]
Oh good it's not just me, I have the same issue as OP tried to make my own Heroku raid finder with the one-button setup. Everything also went fine until I tried to follow raids and it was also blank.
![image](https://cloud.githubusercontent.com/assets/25748101/22891266/e30d705c-f262-11e6-9d3a-0a399141b9d6.png)
Where are the error logs? Heroku shows that the build succeeded under activity. One thing that I noticed is that the version was v0.3.3-SNAPSHOT which was different from the public one v0.3.2 0b847b5.

**Comment by walfie** [comment]
if you go to the app dashboard (`http://dashboard.heroku.com/apps/your-app-name-here`) on the top right there's a "more" button which has a "view logs" option.

or just go to `http://dashboard.heroku.com/apps/your-app-name-here/logs`

The build succeeded because it doesn't attempt to use the twitter credentials at build time, only at runtime.

the snapshot version is because the heroku button deploys the current master branch by default. the only code changes made between v0.3.2 and the current master branch are documentation-related, so the code itself is the same.

**Comment by VictusNoctus** [comment]
Oh man, I tried remaking the app and now the names show up. Sorry bout that, guess it could've been a credential thing, maybe an extra space somewhere? (I'm wondering if my PC could've stalled and something went wrong while building the app).

Uhm while on this topic, I notice I'm missing some raids such as BahaHL, reading the low priority issue topic, do I have to keep my raid finder open to have them added to the list? (Since for now I'm the sole user of it.)

and thanks for everything!

**Comment by walfie** [comment]
it's built on Heroku's side, so I don't think that would be an issue.

anyway, yeah unfortunately free Heroku has a limitation where it'll put the server to sleep if there's no traffic on it for some amount of time. During this time it won't be able to get any new tweets, and there's a startup delay when it starts receiving traffic again.
