### ISSUE TITLE
Want Implent to own VPS server

### ISSUE THREAD

**Issue by testerslol123** [walfie/gbf-raidfinder#106]
Dear Developers,
I have read the code, but is any of this can implent to VPS?
Like digital ocean; https://www.digitalocean.com/

Also is there any tips for host in VPS?

Need suggestion here

*Awesome it is 👍  for using Scala language;
I'm thinking if any language there, I can use for

**Comment by Laforeta** [comment]
I happen to be working on it at the moment. Once I get it working I might be able to contribute a step by step guide or better, a Docker image for rapid deployment.

**Comment by walfie** [comment]
gbf-raidfinder uses [sbt-native-packager](https://github.com/sbt/sbt-native-packager) so you should be able to run it on any platform that supports Java. You can check [the docs](http://www.scala-sbt.org/sbt-native-packager/gettingstarted.html#run-the-app).

sbt-native-packager also can create docker images, so if there's demand, I could just publish images to DockerHub

**Comment by testerslol123** [comment]
@Laforeta thanks, dont forget to place the link here; really appreciate :)
@walfie  May I request this? want to implent it to my VPS;

**Comment by Laforeta** [comment]
@walfie thanks, a dockerfile would be much appreciated :)

**Comment by Laforeta** [comment]
Managed to get it working on a linux VPS (Ubuntu 14.04 LTS KVM) and here is a few things I have noticed:

1. Building from source requires 1GB+ free ram or it will fail. Installation on low end servers will have to be done via a byte code package. 

2. For some reason the build script did not compile the fully optimised client code but did produce the fastopt version. This caused a problem as remotely loaded index.html will try to use the former which does not exist. It's possible to get around this issue with a redirect or by directly editing the html file but this feels rather hacky. Any idea why this might be the case? I had a look in the log file and there are no obvious errors I could point out. 

3. Websockets work reasonably well through Cloudflare. There is about 500ms of additional latency which could be better or worse depending on your location. And it might help those who have connection issues due to their ISP.

**Comment by walfie** [comment]
@Laforeta Regarding (2), which method did you use to build/deploy? was it `sbt stage`, and then copy the files from `target/universal/stage` to the server and run the script at `target/universal/stage/bin/gbf-raidfinder`?

**Comment by walfie** [comment]
I've published a Docker image to DockerHub and added some docs:
https://github.com/walfie/gbf-raidfinder/blob/master/docs/deployment/docker.md

**Comment by Laforeta** [comment]
@walfie yes, that did the trick - thank you. sbt is something new to me and I really had no clue how to build it for release. 

I will have a play with your docker image before getting to write the guide. Thanks again.

**Comment by Laforeta** [comment]
Is anyone still looking for detailed instructions to run this on a VPS? I will leave some instructions for how to set this up on Ubuntu/Debian. 

1. Install docker by following the guide below, if you have Docker installed already make sure it is newer than v1.9 as some early versions have problems handling environmental variables with dot (.) symbols in them. 
    https://docs.docker.com/engine/installation/linux/ubuntu/

2. Follow Walfie's guide (    https://github.com/walfie/gbf-raidfinder/blob/master/docs/deployment/docker.md) with minor alterations:
    The container should be run with a command like the following
    `docker run -d -p 9000:9000 --restart unless-stopped --env-file /path/to/env walfie/gbf-raidfinder`
    The -d switch ensures the container runs in detached mode so terminal access is maintained

3. Install nginx following the official guide below
    https://www.nginx.com/resources/wiki/start/topics/tutorials/install/

4. Generate a config file using the template below, make sure to fill in your domain name if using one
    https://gist.github.com/Laforeta/34da32ebc029abf1a1bb05004a5ceddf
    Copy it to `/etc/nginx/sites-enabled/` And run `nginx -s reload` to apply the changes, your site will be accessible over http

If you are running another web server such as Apache they could be used as well by passing incoming connections to 127.0.0.1:9000 and allow websockets to be proxied as well. In any case do not expose the app directly on port 80 without some form of access control.

**Comment by testerslol123** [comment]
nice @Laforeta , I will try it on my VPS and tell the result here;
since I usually use Nginx and VPS for website development :)
