### ISSUE TITLE
Attribution and Licensing

### ISSUE THREAD

**Issue by Laforeta** [walfie/gbf-raidfinder#109]
Hi Walfie, 

I've set up an instance of gbf-raidfinder on [my own server](https://gbf-raidfinder.la-foret.me/) and so far it appears to run splendidly - thank you very much. I am just wondering is there any licensing and attribution issues I need to be aware of? 

Case in point, the docker image as well as the sbt package generated from the main repository contains a google analytics ID which I assume belongs to you. Am I allowed to strip this out or replace it with my own? 

Thanks again
Laforet

**Comment by walfie** [comment]
I am usually incredibly confused by licenses, but I'm going to say... MIT license? Realistically, you can do whatever you want with it, but I guess I should add an actual license file to the repo at some point.

You can remove the analytics code or use your own. At the moment, since it's a static file, I don't know the best way to do it other than editing the hardcoded `index.html` file and republishing the docker image (with `sbt docker:publish` or `sbt docker:publishLocal`)

**Comment by walfie** [comment]
As a side note, related to analytics, there's an endpoint available on the server at `/api/metrics.json` if you just want a quick view of how many concurrent users there are at the moment.

Also do you mind if I refer people to your server if they're having ISP issues with non-HTTPS websockets?

**Comment by Laforeta** [comment]
>MIT license

Excellent, this should keep things simple and straightforward. 

>As a side note, related to analytics, there's an endpoint available on the server at /api/metrics.json if you just want a quick view of how many concurrent users there are at the moment.

This is quite useful - thank you. 

>Also do you mind if I refer people to your server if they're having ISP issues with non-HTTPS websockets?

Not at all. Feel free to spread the word or add a link to the error page of your Heroku apps if you think this is going to help. So far I have only shared this site with [reddit](https://www.reddit.com/r/Granblue_en/comments/5szrqu/backup_gbfraidfinder_with_https/) but performance seems stable so more users shouldn't be a problem.
