### ISSUE TITLE
Viramate Web API

### ISSUE THREAD

**Issue by luminairre** [walfie/gbf-raidfinder#118]
Hi Walfie, any chance Viramate web API will be implemented? You can find it on Viramate > Options > Web API.

Someone did a grease monkey addon for it,
https://greasyfork.org/pt-BR/scripts/30760-gbf-raidfinder-viramate-web-api-integration/code

Thanks!

**Comment by walfie** [comment]
Probably not, sorry. As you may have noticed, it's been a while since I've made any real changes to the codebase..

However, I'm currently working on a rewrite of gbf-raidfinder as a separate project, and for that one, I'd like to add Viramate integration. No idea when it will be ready though, but it'll probably be a while.
