### ISSUE TITLE
Raids below lv100 are not listed in the list of raids

### ISSUE THREAD

**Issue by jackfang888** [walfie/gbf-raidfinder#138]
Is this a bug or were they intentionally removed?  If intentional, can that be reverted?

**Comment by walfie** [comment]
Twitter suspended the accounts I was using to access the streaming API, so actually no tweets are coming through. The reason the lv100+ bosses are still showing up in the list is because they have a longer retention policy (they're deleted if not seen for 30 days, vs 12 hours for lower level bosses).

I'm assuming you're using granblue-raidfinder.herokuapp.com, so you haven't seen the notice, but I've listed some alternatives you can try here: https://gbf-raidfinder.aikats.us/

**Comment by jackfang888** [comment]
Yes I was using the herokuapp site.  Thanks for the alternatives.  Since it's a Twitter problem, should I close this issue?
