### ISSUE TITLE
Missing Kirin in raid list?

### ISSUE THREAD

**Issue by Bakamoto** [walfie/gbf-raidfinder#85]
Thanks for all the hard work : ) all the raids seem to be available except for Kirin (黒麒麟). Will this be added in the future?

**Comment by walfie** [comment]
Hmm weird, it was there before. I'll take a look tomorrow.

**Comment by walfie** [comment]
It looks like the issue is probably related to the fact that Heroku Redis (which I am using to cache the boss list) has weekly maintenance windows which don't preserve data after restart. I'm going to switch to Redis Cloud which will hopefully have better uptime and persistence.

This should hopefully be fixed in the next release.

**Comment by Bakamoto** [comment]
much appreciated ^^
